// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqjdrrbxpccqqtchzixg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxamRycmJ4cGNjcXF0Y2h6aXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTM5NTksImV4cCI6MjA2NzU4OTk1OX0.eabOlaC8Cj6g33hjAXk4HfY78onUTnnprIZfaUwwrVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});